In [1]:
import numpy as np 

array1=np.array([1, 2, 3, 4])
print(array1)

[1 2 3 4]


In [8]:
import numpy as np 

tal = np.arange(10)

print(tal)

ettor = np.ones(8)
print(ettor)

[0 1 2 3 4 5 6 7 8 9]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
import numpy as np 
import random as rnd 

utfall = np.zeros(6, dtype = int)
print(utfall)

antal_kast = 100
for i in range (antal_kast):
    kast = rnd.randint (1,6)
    utfall [kast-1] += 1
    print(utfall)


[0 0 0 0 0 0]
[0 0 0 1 0 0]
[0 0 0 1 1 0]
[0 0 0 2 1 0]
[0 1 0 2 1 0]
[0 1 0 3 1 0]
[0 1 0 4 1 0]
[0 1 1 4 1 0]
[0 1 1 5 1 0]
[0 1 1 5 2 0]
[0 1 1 5 2 1]
[0 1 1 6 2 1]
[0 2 1 6 2 1]
[0 2 1 6 3 1]
[0 2 1 6 3 2]
[0 2 1 6 4 2]
[0 2 1 7 4 2]
[0 2 2 7 4 2]
[0 2 2 7 4 3]
[0 2 2 7 5 3]
[0 2 2 7 6 3]
[0 2 2 8 6 3]
[0 3 2 8 6 3]
[0 3 3 8 6 3]
[0 3 3 9 6 3]
[1 3 3 9 6 3]
[1 3 3 9 7 3]
[1 3 3 9 7 4]
[1 3 4 9 7 4]
[1 4 4 9 7 4]
[2 4 4 9 7 4]
[2 4 4 9 8 4]
[3 4 4 9 8 4]
[3 4 5 9 8 4]
[ 3  4  5 10  8  4]
[ 3  4  6 10  8  4]
[ 3  4  6 10  9  4]
[ 3  4  7 10  9  4]
[ 3  4  8 10  9  4]
[ 3  4  9 10  9  4]
[ 4  4  9 10  9  4]
[ 5  4  9 10  9  4]
[ 5  4  9 10  9  5]
[ 5  4 10 10  9  5]
[ 5  5 10 10  9  5]
[ 5  5 10 10 10  5]
[ 5  5 10 10 11  5]
[ 5  5 11 10 11  5]
[ 5  6 11 10 11  5]
[ 5  6 12 10 11  5]
[ 5  6 12 10 12  5]
[ 5  6 12 10 12  6]
[ 5  7 12 10 12  6]
[ 5  7 13 10 12  6]
[ 5  7 13 10 13  6]
[ 5  7 13 10 14  6]
[ 6  7 13 10 14  6]
[ 6  7 13 10 15  6]
[ 6  7 13 10 15  7]
[ 6  7 13 10 16  7]
[ 6 