In [4]:
# 1 a)

# importar numpy för att det behövs
import numpy as np 

# skapar en array med 10 element 1 till 10
array=np.array([1,2,3,4,5,6,7,8,9,10])

# printar arrayen jag skapade
print(array)

# b)

# gör samma här som i a) men med 21 element istället -10 till 10
array2=np.array([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10])

# printar den andra arrayen jag skapade
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [8]:
# 2

# importar numpy och math för att edt behövs
import numpy as np 
import math  

# skapar en array med 10 element 10 till 100
array=np.array([10,20,30,40,50,60,70,80,90,100])

# printar bara arrayen
print(array)

# printar arrayen fast multiplicerar med 10
print(array*10)

[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]


In [ ]:
# 3 

